FlightAdministrator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival Airports)</relationshipLabel>
    <relationshipName>FlightArrivalAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Departure Airport)</relationshipLabel>
    <relationshipName>FlightDepartureAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight Distance (km)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightAdministrator/force-app/main/default/classes/FlightSelector.cls
public class FlightSelector {

    /**
     * Retrieves all flights.
     *
     * @return list of flights
     */
    public static List<Flight__c> fetchFlights() {
        return [
            SELECT
                Id,
                Name,
                DepartureAirport__c,
                ArrivalAirport__c,
                FlightDistance__c
            FROM
                Flight__c
        ];
    }

    /**
     * Retrieves flight record by DepartureAirport__c and ArrivalAirport__c.
     * @param departureAirportId departure airport id
     * @param arrivalAirportId arrival airport id
     *
     * @return flight record
     */
    public static Flight__c fetchFlightByDepartureAirportIdAndArrivalAirportId(Id departureAirportId, Id arrivalAirportId) {
        return [
            SELECT
                Id,
                Name,
                DepartureAirport__c,
                ArrivalAirport__c,
                FlightDistance__c
            FROM
                Flight__c
            WHERE 
                DepartureAirport__c = :departureAirportId
                AND ArrivalAirport__c = :arrivalAirportId
            LIMIT 1
        ];
    }
}