FlightAdministrator/force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Airport__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <label>Geolocation</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Airport__c/fields/IataCode__c.field-meta.xml
<CustomField>
    <fullName>IataCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IATA Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FlightAdministrator/force-app/main/default/classes/AirportSelector.cls
public class AirportSelector {
    
    /**
     * Retrieves all airports.
     *
     * @return list of airports
     */
    public static List<Airport__c> fetchAirports() {
        return [
            SELECT
                Id,
                Name,
                City__c,
                Country__c,
                Geolocation__c,
                IataCode__c
            FROM
                Airport__c
        ];
    }
    
    /**
     * Retrieves airports by ids.
     * @param airportIds airport ids 
     *
     * @return map of airports
     */
    public static Map<Id, Airport__c> fetchAirportsByIds(Set<Id> airportIds) {
        return new Map<Id, Airport__c> ([
            SELECT
                Id,
                Name,
                City__c,
                Country__c,
                Geolocation__c,
                Geolocation__Latitude__s,
                Geolocation__Longitude__s,
                IataCode__c
            FROM
                Airport__c
            WHERE
                Id IN :airportIds
        ]);
    }
}