FlightAdministrator/force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival Airports)</relationshipLabel>
    <relationshipName>FlightArrivalAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Departure Airport)</relationshipLabel>
    <relationshipName>FlightDepartureAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight Distance (km)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightAdministrator/force-app/main/default/classes/FlightService.cls
/**
 * Class contains service methods for Flight__c obj.
 */
public class FlightService {

    /**
    * Insert new Flight record based on departure airport and arrival airport.
    * @param departureAirportId departure airport id
    * @param arrivalAirportId arrival airport id
    */
    public static void handleSaveFlight(Id departureAirportId, Id arrivalAirportId) {
        if(departureAirportId == null || arrivalAirportId == null) {
            return;
        }

        insert new Flight__c(
            DepartureAirport__c = departureAirportId,
            ArrivalAirport__c = arrivalAirportId
        );
    }
    
    /**
    * Handler for Flight Distance. Calculates FlightDistance__c based on DepartureAirport__c and ArrivalAirport__c.
    * @param flights list of flights
    */
    public static void handleFlightDistance(List<Flight__c> flights) {
        Set<Id> airportIds = new Set<Id>();
        
        for(Flight__c flight : flights) {
            airportIds.add(flight.DepartureAirport__c);
            airportIds.add(flight.ArrivalAirport__c);
        }

        Map<Id, Airport__c> airportIds2Airport = AirportSelector.fetchAirportsByIds(airportIds);

        for(Flight__c flight : flights) {
            if(
                airportIds2Airport.keySet().contains(flight.DepartureAirport__c)
                && airportIds2Airport.keySet().contains(flight.ArrivalAirport__c)
            ) {
                flight.FlightDistance__c = UtilsMethods.calculateDistanceByCoordinates(
                    airportIds2Airport.get(flight.DepartureAirport__c).Geolocation__Latitude__s,
                    airportIds2Airport.get(flight.DepartureAirport__c).Geolocation__Longitude__s,
                    airportIds2Airport.get(flight.ArrivalAirport__c).Geolocation__Latitude__s,
                    airportIds2Airport.get(flight.ArrivalAirport__c).Geolocation__Longitude__s,
                    Constants.EARTH_RADIUS_IN_KILOMETERS
                );
            }
        }
    }
}