FlightAdministrator/force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FL-{000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival Airports)</relationshipLabel>
    <relationshipName>FlightArrivalAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Departure Airport)</relationshipLabel>
    <relationshipName>FlightDepartureAirport</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightAdministrator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight Distance (km)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightAdministrator/force-app/main/default/classes/FlightServiceTest.cls
@IsTest
private class FlightServiceTest {

    @TestSetup
    static void initData() {
        insert new List<Airport__c>{
            AirportTestDataFactory.buildAirportWithNameWithIataCodeWithLatitudeWithLongitude(
                false,
                AirportTestData.FIRST_AIRTPORT_NAME_TEST,
                AirportTestData.FIRST_IATA_CODE_TEST,
                AirportTestData.FIRST_LATITUDE_TEST,
                AirportTestData.FIRST_LONGITUDE_TEST
            ),
            AirportTestDataFactory.buildAirportWithNameWithIataCodeWithLatitudeWithLongitude(
                false,
                AirportTestData.SECOND_AIRTPORT_NAME_TEST,
                AirportTestData.SECOND_IATA_CODE_TEST,
                AirportTestData.SECOND_LATITUDE_TEST,
                AirportTestData.SECOND_LONGITUDE_TEST
            )
        };
    }

    @IsTest
    static void handleFlightDistanceTest() {
        List<Airport__c> testAirports = AirportSelector.fetchAirports();

        Test.startTest();

        insert new Flight__c(
            DepartureAirport__c = testAirports.get(0).Id,
            ArrivalAirport__c = testAirports.get(1).Id
        );

        Test.stopTest();

        System.assertEquals(1869.309193621214, FlightSelector.fetchFlights().get(0).FlightDistance__c);
    }
}